
- name: prepare RTBKit dependencies
  command: make dependencies
  sudo_user: "{{ rtbkit_user }}"
  args:
      chdir: "{{ rtbkit_framework }}"

- name: compile RTBkit
  shell: make compile
  sudo_user: "{{ rtbkit_user }}"
  args:
    chdir: "{{ rtbkit_framework }}"
