---
- name: install dependencies
  apt: pkg={{ item }} update_cache=yes state=present
  with_items: apt_pkgs

- name: install PIP
  apt: >
      pkg=python-pip
      update_cache=yes
      state=present

- name: upgrade to the newest pip, so that we don't depend on the system version
  shell: pip install --upgrade pip
  register: pip_result
  changed_when: "'Requirement already up-to-date' not in pip_result.stdout"

- name: install graphite required components
  shell: /usr/local/bin/pip install --allow-all-external {{ item }} --allow-unverified {{ item }}
  with_items: pip_pkgs
  register: pip_result
  changed_when: "'Requirement already satisfied' not in pip_result.stdout"
