 - name: download pycairo
   get_url: >
    url={{ pycairo_download_url }}/py2cairo-{{ pycairo_version }}.tar.bz2
    dest=/tmp/py2cairo-{{ pycairo_version }}.tar.bz2
   sudo_user: "{{ rtbkit_user }}"

 - name: extract pycairo tarball
   shell: >
     tar -xjf /tmp/py2cairo-{{ pycairo_version }}.tar.bz2 -C /tmp
   sudo_user: "{{ rtbkit_user }}"

 - name: configure cairo
   command: ./waf configure
    chdir=/tmp/py2cairo-{{ pycairo_version }}
   sudo_user: "{{ rtbkit_user }}"

 - name: build cairo
   command: ./waf build
    chdir=/tmp/py2cairo-{{ pycairo_version }}
   sudo_user: "{{ rtbkit_user }}"

 - name: install cairo
   command: ./waf install
    chdir=/tmp/py2cairo-{{ pycairo_version }}
