
 - name: clone RTBkit repo
   git: >
    repo=https://github.com/rtbkit/rtbkit.git
    dest={{ rtbkit_framework }}
    version=ubuntu14
    recursive=no
    update=yes
    force=yes
    accept_hostkey=yes

 - name: copy sample.mk as local.mk config file
   command: cp jml-build/sample.local.mk local.mk
   args:
    chdir: "{{ rtbkit_framework }}"

 - name: create build directory
   file: >
    path={{ rtbkit_framework }}/rtbkit/build
    state=directory
